version: '3.8'

services:

  db:
    image: "postgres:9.6-alpine"
    container_name: postgres-container
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=inn_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  inn-management-app:
    build: ./
    container_name: inn-management-app
    environment:
      - DB_SERVER=db
      - POSTGRES_DB=inn_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8080:8080
    links:
      - db

#  inn-management-ui:
#    build: ./frontend
#    container_name: inn-management-ui
#    ports:
#      - 4200:80
#    links:
#      - inn-management-app

volumes:
  data: